name: Makefile CI

on:
  push:
    paths:
      - '**.h'
      - '**.cpp'
      - 'makefile'
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
#     - name: configure
#       run: ./configure
      
    - name: Compile
      run: make compile
      
    - name: Run tests
      run: make test DEBUG=-DTEST
      
#     - name: Run distcheck
#       run: make distcheck
